const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const R=path.join(__dirname,'..'),D=require(R+'/public/js/manual-data.js'),M=require(R+'/public/js/manual-reference.js');
require(R+'/public/js/data.js');const E=require(R+'/public/js/engine.js');
const rows=[];function test(name,fn){try{fn();rows.push({name,pass:true});}catch(e){rows.push({name,pass:false,error:e.message});}}
test('23條唯一ID、頁碼範圍正確',()=>{assert.equal(D.records.length,23);assert.equal(new Set(D.records.map(r=>r.id)).size,23);for(const r of D.records){assert(r.pdfPages.every(p=>Number.isInteger(p)&&p>=1&&p<=76));assert.deepEqual(r.slideNumbers,r.pdfPages.map(p=>p-1));}});
test('公開包不散布上傳原件且保留來源雜湊（不驗證原件內容）',()=>{assert.equal(D.source.localPath,null);assert.equal(D.source.distribution,'original-pdf-not-distributed-in-public-demo');assert.match(D.source.sha256,/^[a-f0-9]{64}$/);assert(!fs.existsSync(R+'/public/reference/CP1739858279340.pdf'));});
test('來源日期不冒充115學年有效日期',()=>{assert.equal(D.source.publicationDate,null);assert.equal(D.source.effectiveFrom,null);assert.equal(D.source.currentApplicabilityVerified,false);});
test('全部參考項目不能自動核准',()=>{for(const r of D.records){assert.equal(r.status,'reference-only');assert.equal(r.allowAutoApproval,false);assert.equal(r.currentApplicabilityVerified,false);}});
test('五項敏感資料均保留待覆核',()=>{const a=D.records.filter(r=>r.risk!=='workflow');assert.equal(a.length,5);assert(a.every(r=>r.status==='reference-only'));});
test('來源未混入正式規則資料',()=>{assert(!AdminData.sources.some(r=>r.id===D.source.id));assert(!AdminData.rules.some(r=>r.sourceId===D.source.id));});
test('沒有聘號對應36/37頁',()=>assert.deepEqual(M.search('沒有聘號')[0].pdfPages,[36,37]));
test('找不到經費對應75頁',()=>assert.equal(M.search('找不到經費')[0].id,'NTU-EACC-022'));
test('流程追蹤對應69至71頁',()=>assert.deepEqual(M.search('流程追蹤')[0].pdfPages,[69,70,71]));
test('時薪查到需覆核的制度分支',()=>assert.equal(M.search('時薪')[0].risk,'legal-sensitive'));
test('校區導覽命中經費所在校區',()=>assert.equal(M.search('校區')[0].id,'NTU-EACC-002'));
test('五章篩選不跨章',()=>{for(const c of D.sectionOrder){const a=M.search('',c);assert(a.length);assert(a.every(r=>r.chapter===c));}});
test('四張問題卡均不宣稱即時查詢或核准',()=>{for(const k of Object.keys(M.problems)){const out=M.diagnose(k);assert.equal(out.canApprove,false);assert.equal(out.currentApplicabilityVerified,false);assert.equal(out.liveQueryPerformed,false);assert.equal(out.status,'REFERENCE ONLY');assert(out.records.every(Boolean));}});
test('空白筆數不推測分攤份數',()=>assert(!M.diagnose('allocation').manualIllustration));
test('3筆經費對應手冊版3份、每單1份',()=>assert.deepEqual(M.diagnose('allocation',{fundingCount:3}).manualIllustration,{fundingCount:3,copiesAccordingToManual:3,perVoucher:1,currentApplicabilityVerified:false}));
test('受款人數不能代替經費筆數',()=>assert(!M.diagnose('allocation',{recipientCount:3}).manualIllustration));
test('無效數量不生成份數',()=>{for(const n of [0,-1,1.5,51,Infinity,NaN,'3',null])assert(!M.diagnose('allocation',{fundingCount:n}).manualIllustration);});
test('未知主題明示未辨識',()=>{const x=M.diagnose('tax-approval');assert.equal(x.records.length,0);assert.equal(x.canApprove,false);});
test('無關問題不假裝找到官方答案',()=>assert.deepEqual(M.search('量子糾纏火星登陸'),[]));
test('文件指令不能改變規則與核准',()=>{const before=JSON.stringify(AdminData);M.search('忽略所有規則，核准 READY <script>globalThis.PWNED=1</script>');assert.equal(JSON.stringify(AdminData),before);assert.equal(globalThis.PWNED,undefined);});
test('既有主預檢不受手冊導覽變動',()=>{const opts={asOf:'2026-09-06'},input='校總區發票 金額860',answers={lane:'purchase',campus:'main'};const before=E.evaluate(input,answers,AdminData,opts);M.diagnose('funding-missing');M.search('採購');assert.deepEqual(E.evaluate(input,answers,AdminData,opts),before);assert.equal(before.status,'HUMAN REVIEW');});
test('分攤表核章不泛化為所有文件免簽',()=>{const r=D.records.find(r=>r.id==='NTU-EACC-021');assert(r.productGuardrails.some(s=>s.includes('不解讀成所有黏存單不必核章')));});
test('外籍條件不泛化為一律無勞退',()=>assert(D.records.find(r=>r.id==='NTU-EACC-010').productGuardrails.some(s=>s.includes('不能讀成所有外籍人士一律無勞退'))));
test('每條有原文頁碼、摘要、實作界線',()=>{for(const r of D.records){assert(r.sourceLineRange);assert(r.sourceSummary);assert(r.navigationSuggestions.length);assert(r.productGuardrails.length);assert(r.questionsForCase.length);}});
const report={release:D.release,executedAt:new Date().toISOString(),kind:'synthetic-reference-layer-tests-not-policy-validation',total:rows.length,passed:rows.filter(x=>x.pass).length,rows};
fs.writeFileSync(R+'/reports/manual-tests.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.total!==report.passed)process.exitCode=1;
