'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),D=path.join(root,'dist');
const rows=[];
const test=(name,f)=>{try{f();rows.push({name,pass:true});}catch(e){rows.push({name,pass:false,error:e.message});}};
const read=p=>fs.readFileSync(path.join(D,p),'utf8');
const caps=JSON.parse(read('capabilities.json'));
const all=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(x=>x.isDirectory()?all(path.join(dir,x.name)):[path.join(dir,x.name)]);
const files=all(D);
test('No Python backend, environment secrets, runtime data, or uploaded manual in public output',()=>{for(const p of files)assert(!/(server\.py|\.env|CP1739858279340\.pdf|\/runtime\/|\/reports\/|\/uploads\/|\/private\/)/.test(p));});
test('No cloud upload or storage capability advertised',()=>{assert.equal(caps.acceptsCloudUploads,false);assert.equal(caps.cloudCaseStorage,false);});
test('No configured SSO and no official submission capability',()=>{assert.equal(caps.ssoEnabled,false);assert.equal(caps.identityProviderConfigured,false);assert.equal(caps.officialSubmissionEnabled,false);});
test('Images and PDF are not advertised as recognized',()=>{assert.equal(caps.extraction.image,false);assert.equal(caps.extraction.pdf,false);assert(read('index.html').includes('照片／PDF 僅預覽'));});
test('Public mode is loaded before business scripts',()=>{for(const p of ['index.html','workbench.html'])assert(read(p).indexOf('js/deployment-mode.js')<read(p).indexOf('js/data.js'));});
test('Browser network submission blocked by CSP in both entry points',()=>{for(const p of ['index.html','workbench.html']){assert(read(p).includes("connect-src 'none'"));assert(read(p).includes("form-action 'none'"));assert(read(p).includes("script-src 'self'"));}});
test('No password field and no external executable dependencies',()=>{for(const p of files.filter(x=>x.endsWith('.html'))){const h=fs.readFileSync(p,'utf8');assert(!/type\s*=\s*["']password/i.test(h));assert(!/<script[^>]+src=["']https?:/i.test(h));}});
test('No inline script in main public entry points',()=>{for(const p of ['index.html','workbench.html'])assert(!/<script(?![^>]*\bsrc=)[^>]*>/i.test(read(p)));});
test('Relative local HTML assets and links resolve',()=>{for(const p of files.filter(x=>x.endsWith('.html'))){const h=fs.readFileSync(p,'utf8');for(const [,v]of h.matchAll(/(?:src|href)=["']([^"']+)["']/g)){if(/^(?:[a-z]+:|#|\/\/)/i.test(v))continue;const pathname=v.split(/[?#]/)[0];if(!pathname)continue;assert(!pathname.startsWith('/'),'Root-relative URL breaks project subpath: '+v);assert(fs.existsSync(path.resolve(path.dirname(p),pathname)),'Broken URL: '+v);}}});
test('Manual references explain omission instead of linking to a missing PDF',()=>{assert(read('js/manual-ui.js').includes('reference/index.html'));assert(read('reference/index.html').includes('未重新散布'));});
test('Permission checks are not replaced by SSO or client flags',()=>{require('../public/js/data.js');const S=require('../public/js/simple-core.js');let x=S.fromText('發票 金額：860');S.update(x,{purpose:'公開範例',fundCode:'KNOWN',officialApproval:true});S.confirm(x);assert.equal(S.packet(x,AdminData).officialSubmission,false);assert(S.pending(x).some(t=>t.includes('授權')));});
test('Public output passes common private-key and provider-token format scan (not a comprehensive secret audit)',()=>{const patterns=[/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,/gh[pousr]_[A-Za-z0-9]{25,}/,/github_pat_[A-Za-z0-9_]{25,}/,/sk-(?:proj-)?[A-Za-z0-9_-]{32,}/,/pxc_[A-Za-z0-9_-]{30,}/];for(const p of files.filter(x=>/\.(html|js|json|css|txt)$/.test(x)))for(const q of patterns)assert(!q.test(fs.readFileSync(p,'utf8')),'Possible secret: '+p);});
test('Pages workflow publishes only dist, not repository root',()=>{const y=fs.readFileSync(path.join(root,'.github/workflows/pages.yml'),'utf8');assert(y.includes('path: dist'));assert(y.includes("github.event_name != 'pull_request'"));assert(y.includes('pages: write'));});
test('Vercel output is dist and no backend rewrite is enabled',()=>{const c=JSON.parse(fs.readFileSync(path.join(root,'vercel.json')));assert.equal(c.outputDirectory,'dist');assert.equal(c.installCommand,'');assert(!c.rewrites);assert(c.headers[0].headers.some(x=>x.key==='Content-Security-Policy'&&x.value.includes("frame-ancestors 'none'")));});
test('No local or session storage API in the entry UI',()=>{const src=read('js/simple.js');assert(!/(localStorage|sessionStorage)\.(setItem|getItem)/.test(src));});
const report={executedAt:new Date().toISOString(),total:rows.length,passed:rows.filter(x=>x.pass).length,scope:'Synthetic tests and static release checks. No remote deployment, field accuracy, identity, or school API test.',rows};
fs.writeFileSync(path.join(root,'reports/release-tests.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.total!==report.passed)process.exit(1);
