'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
require('../public/js/data.js');const E=require('../public/js/engine.js'),S=require('../public/js/simple-core.js');
const results=[];function test(name,f){try{f();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}}
let s;
test('文字金額與民國日期候選',()=>{s=S.fromText('發票\n日期：115/09/06\n合計：860');assert.equal(s.fields.amount,'860');assert.equal(s.fields.documentDate,'2026-09-06');assert.equal(s.lane,'purchase');});
test('用途與經費不從發票猜測',()=>{assert.equal(s.fields.purpose,'');assert.equal(s.fields.fundCode,'');});
test('已知欄位確認前不可標成已確認',()=>assert.equal(S.packet(s,AdminData).confirmedKnownFields,false));
test('未填用途不能建立已確認草稿',()=>assert.throws(()=>S.confirm(s)));
test('用途輸入後可確認部分草稿',()=>{S.update(s,{purpose:'合成活動材料'});S.confirm(s);assert.equal(s.confirmedRevision,s.revision);});
test('確認部分草稿仍不是正式送件或核准',()=>{const p=S.packet(s,AdminData);assert.equal(p.officialSubmission,false);assert.equal(p.officialApproval,false);assert.equal(p.paymentConfirmed,false);assert.equal(p.officialReceipt,null);});
test('未知經費保留為待確認',()=>assert.ok(S.pending(s).includes('經費來源及使用授權')));
test('輸入經費也不冒充授權',()=>{S.update(s,{fundCode:'USER-ENTERED'});assert.ok(S.pending(s).includes('經費使用授權（尚未驗證）'));});
test('欄位改動使前次確認失效',()=>assert.equal(s.confirmedRevision,null));
test('更改相同值不增加版本',()=>{const r=s.revision;S.update(s,{fundCode:'USER-ENTERED'});assert.equal(s.revision,r);});
test('不接受未定義的授權欄位',()=>{S.update(s,{officialApproval:'yes'});assert.equal(s.fields.officialApproval,undefined);});
test('金額格式支援千分位與兩位小數',()=>{assert.ok(S.money('1,250.50'));});
test('禁止負數、零、指數、非數值、超範圍金額',()=>{for(const v of ['0','-3','NaN','1e3','Infinity','1.234','1000000001'])assert.equal(S.money(v),false);});
test('多金額不選其中之一',()=>{const d=S.fromText('發票 金額：100\n總計：200');assert.equal(d.fields.amount,'');assert.ok(d.warnings.some(x=>x.includes('多個不同金額')));});
test('無效日期不採用',()=>assert.equal(S.fromText('日期：2026/02/30').fields.documentDate,''));
test('混合案件保留人工檢查',()=>{const d=S.fromText('我要加保並报銷發票');assert.equal(d.lane,'mixed');assert.equal(S.preflight(d,AdminData).status,'HUMAN REVIEW');});
test('未讀取照片不假稱已掃描',()=>{const d=S.fromText('',{sourceType:'unread-file',incomplete:true});assert.ok(S.pending(d).includes('原始文件完整內容'));assert.equal(S.packet(d,AdminData).source.complete,false);});
test('預檢核心沒有被简化界面跳過',()=>{assert.notEqual(S.preflight(s,AdminData).status,'READY');assert.ok(S.preflight(s,AdminData).questions.length);});
test('過期或異動來源保留停用條件',()=>{const d=S.fromText('聘僱 勞保');const p=S.preflight(d,AdminData,Object.fromEntries(AdminData.sources.map(x=>[x.id,'changed'])));assert.equal(p.status,'HUMAN REVIEW');});
test('合成標記單獨保存且不外溢至新案',()=>{const d=S.fromText('發票金額：860',{synthetic:true});assert.equal(S.packet(d,AdminData).synthetic,true);assert.equal(S.fromText('發票金額：900').synthetic,false);});
test('下載資料不含原文與圖片',()=>{const p=S.packet(s,AdminData);assert.equal(p.rawText,undefined);assert.equal(p.source.originalFileIncluded,false);assert.equal(p.source.rawTextIncluded,false);});
test('工作底稿對HTML輸入跳脫',()=>{S.update(s,{purpose:'<img src=x onerror=alert(1)>',payee:'<script>alert(2)</script>'});const html=S.worksheet(s,AdminData);assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img src=x'));assert.ok(!html.includes('<script>alert'));});
test('工作底稿註明未送件及缺件',()=>{const html=S.worksheet(s,AdminData);assert.ok(html.includes('尚未送校方'));assert.ok(html.includes('待確認'));});
const report={version:S.VERSION,tests:results,passed:results.filter(x=>x.pass).length,total:results.length,scope:'新簡易介面資料狀態與匯出；不代表真實报帳成功率'};fs.writeFileSync(path.join(__dirname,'../reports/ui-v1.2/simple-core-tests.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.passed!==report.total)process.exit(1);
